[ _ ]
schema-version = "0.2"

[[io.buildpacks.group]]
id = "heroku/nodejs-engine"
version = "3.2.14"

[[io.buildpacks.group]]
id = "heroku/procfile"
version = "3.1.2"

[[io.buildpacks.group]]
id = "heroku/nodejs-npm-install"
version = "3.2.14"
